var employeesJSON = [
    {
        'Name': 'Priam Jourdain',
        'Position' :  'AbilitonPROJuniorSoftwareEngineer',
        'CompetenceGroup' :   'Python',
        'Location' :  'Rivne1',
        'CompanyWorkingMonths' :  72,
        'MonthsInCurrentRole' :   11,
        'MonthsWithCurrentManager' :  15,
        'ProjectCount' :  5,
        'MonthsAfterLastPromotion' :  11,
        'MonthsAfterLastPerformanceAppraisal' :   6,
        'LastPerformanceAppraisalScore' :     100.44,
        'PreviousPerformanceAppraisalScore' :     99.53,
        'MonthsAfterLastSalaryReview' :   4,
        'LastSalaryReviewPercentage' :    2.01,
    },
    {
        'Name': 'Ivory Dilip',
        'Position' :  'AbilitonTechnicalLeader',
        'CompetenceGroup' :   'SAR',
        'Location' :  'I.Frankivsk',
        'CompanyWorkingMonths' :  242,
        'MonthsInCurrentRole' :   149,
        'MonthsWithCurrentManager' :  14,
        'ProjectCount' :  5,
        'MonthsAfterLastPromotion' :  149,
        'MonthsAfterLastPerformanceAppraisal' :   11,
        'LastPerformanceAppraisalScore' :     100,
        'PreviousPerformanceAppraisalScore' :     97.78,
        'MonthsAfterLastSalaryReview' :   11,
        'LastSalaryReviewPercentage' :    85.59,
    },
    {
        'Name': 'Kenny Rajneesh',
        'Position' :  'AbilitonIntermediateSoftwareEngineer',
        'CompetenceGroup' :   'DevOps',
        'Location' :  'Lviv3',
        'CompanyWorkingMonths' :  25,
        'MonthsInCurrentRole' :   11,
        'MonthsWithCurrentManager' :  4,
        'ProjectCount' :  4,
        'MonthsAfterLastPromotion' :  11,
        'MonthsAfterLastPerformanceAppraisal' :   6,
        'LastPerformanceAppraisalScore' :     100.18,
        'PreviousPerformanceAppraisalScore' :     100,
        'MonthsAfterLastSalaryReview' :   0,
        'LastSalaryReviewPercentage' :    56,
    }
];

export default employeesJSON;