var employeesJSON = [
    {
        'Name': 'Natalka Zelenko',
        'Position' : 'AbilitonTechnicalLeader',
        'CompetenceGroup' : 'SAR',
        'Location' : 'IFrankivsk',
        'CompanyWorkingMonths' : 46,
        'MonthsInCurrentRole' : 11,
        'MonthsWithCurrentManager' : 8,
        'ProjectCount' : 3,
        'MonthsAfterLastPromotion' : 11,
        'MonthsAfterLastPerformanceAppraisal' : 5,
        'LastPerformanceAppraisalScore' : 98.72,
        'PreviousPerformanceAppraisalScore' : 100,
        'MonthsAfterLastSalaryReview' : 6,
        'LastSalaryReviewPercentage' : 30
    },
    {
        'Name': 'Miron Chayka',
        'Position' : 'AbilitonSeniorSoftwareEngineer',
        'CompetenceGroup' : 'C_C_plus_plus',
        'Location' : 'Lviv3',
        'CompanyWorkingMonths' : 71,
        'MonthsInCurrentRole' : 4,
        'MonthsWithCurrentManager' : 18,
        'ProjectCount' : 4,
        'MonthsAfterLastPromotion' : 4,
        'MonthsAfterLastPerformanceAppraisal' : 4,
        'LastPerformanceAppraisalScore' : 99.62,
        'PreviousPerformanceAppraisalScore' : 98.52,
        'MonthsAfterLastSalaryReview' : 1,
        'LastSalaryReviewPercentage' : 16.42
    },
    {
        'Name': 'Mila Stasiuk',
        'Position' : 'AbilitonPROJuniorSoftwareEngineer',
        'CompetenceGroup' : 'DevOps',
        'Location' : 'LvivHQ',
        'CompanyWorkingMonths' : 11,
        'MonthsInCurrentRole' : 0,
        'MonthsWithCurrentManager' : 11,
        'ProjectCount' : 1,
        'MonthsAfterLastPromotion' : 0,
        'MonthsAfterLastPerformanceAppraisal' : 1,
        'LastPerformanceAppraisalScore' : 100.51,
        'PreviousPerformanceAppraisalScore' : -1,
        'MonthsAfterLastSalaryReview' : 0,
        'LastSalaryReviewPercentage' : 28.94
    },
    {
        'Name': 'Mykyta Vasylyshyn',
        'Position' : 'AbilitonTechnicalLeader',
        'CompetenceGroup' : 'SAR',
        'Location' : 'IFrankivsk',
        'CompanyWorkingMonths' : 46,
        'MonthsInCurrentRole' : 11,
        'MonthsWithCurrentManager' : 8,
        'ProjectCount' : 3,
        'MonthsAfterLastPromotion' : 11,
        'MonthsAfterLastPerformanceAppraisal' : 5,
        'LastPerformanceAppraisalScore' : 98.72,
        'PreviousPerformanceAppraisalScore' : 100,
        'MonthsAfterLastSalaryReview' : 6,
        'LastSalaryReviewPercentage' : 30
    },
    {
        'Name': 'Vsevolod Kohut',
        'Position' : 'AbilitonTechnicalLeader',
        'CompetenceGroup' : 'SAR',
        'Location' : 'IFrankivsk',
        'CompanyWorkingMonths' : 46,
        'MonthsInCurrentRole' : 11,
        'MonthsWithCurrentManager' : 8,
        'ProjectCount' : 3,
        'MonthsAfterLastPromotion' : 11,
        'MonthsAfterLastPerformanceAppraisal' : 5,
        'LastPerformanceAppraisalScore' : 98.72,
        'PreviousPerformanceAppraisalScore' : 100,
        'MonthsAfterLastSalaryReview' : 6,
        'LastSalaryReviewPercentage' : 30
    },
    {
        'Name': 'Svyatoslav Shwetz',
        'Position' : 'AbilitonTechnicalLeader',
        'CompetenceGroup' : 'SAR',
        'Location' : 'IFrankivsk',
        'CompanyWorkingMonths' : 46,
        'MonthsInCurrentRole' : 11,
        'MonthsWithCurrentManager' : 8,
        'ProjectCount' : 3,
        'MonthsAfterLastPromotion' : 11,
        'MonthsAfterLastPerformanceAppraisal' : 5,
        'LastPerformanceAppraisalScore' : 98.72,
        'PreviousPerformanceAppraisalScore' : 100,
        'MonthsAfterLastSalaryReview' : 6,
        'LastSalaryReviewPercentage' : 30
    }
];

export default employeesJSON;